{% set name = "apache-airflow-providers-cncf-kubernetes" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-cncf-kubernetes-{{ version }}.tar.gz
  sha256: 10bca151efdb01772f25bc8e45738df4331910cd7b493bfc68d672866f1dff6f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - apache-airflow >=2.3.0
    - asgiref >=3.5.2
    - cryptography >=2.0.0
    - python-kubernetes >=21.7.0,<24
    - kubernetes_asyncio >=18.20.1,<25

test:
  imports:
    - airflow.providers.cncf.kubernetes
    - airflow.providers.cncf.kubernetes.backcompat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-cncf-kubernetes package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
