{% set name = "apache-airflow-providers-cncf-kubernetes" %}
{% set version = "9.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_cncf_kubernetes-{{ version }}.tar.gz
  sha256: eb34bea6743942bfbb290b306f06de8d69bcd10c3f76f19132606758b44d7489

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9,<4.dev0
    - aiofiles >=23.2.0
    - apache-airflow >=2.8.0
    - asgiref >=3.5.2
    - cryptography >=41.0.0
    - google-re2 >=1.0
    - python-kubernetes >=29.0.0,<=31.0.0
    - kubernetes_asyncio >=29.0.0,<=31.0.0

test:
  imports:
    - airflow.providers.cncf.kubernetes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-cncf-kubernetes for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/cncf/kubernetes/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
