{% set name = "apache-airflow-providers-cncf-kubernetes" %}
{% set version = "10.8.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_cncf_kubernetes-{{ version }}.tar.gz
  sha256: cd4dabb06e65d61223ffdfe938c5c0dfcbd32cc4ce2949b24193f006499e887d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - aiofiles >=23.2.0
    - apache-airflow >=2.10.0
    - asgiref >=3.5.2
    - cryptography >=41.0.0
    - python-kubernetes >=32.0.0,<33.0.0
    - kubernetes_asyncio >=32.0.0,<33.0.0

test:
  imports:
    - airflow.providers.cncf.kubernetes
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-cncf-kubernetes for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/cncf/kubernetes/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
