{% set name = "apache-airflow-providers-cncf-kubernetes" %}
{% set version = "10.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_cncf_kubernetes-{{ version }}.tar.gz
  sha256: 4970a84549b2c9dfba2b5983e77959c4fca668fe6430be61216c2b78c6044960

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - urllib3 >=2.1.0,!=2.6.0
    - python >={{ python_min }}
    - aiofiles >=23.2.0
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-compat >=1.10.1
    - asgiref >=3.5.2
    - cryptography >=41.0.0,<46.0.0
    - python-kubernetes >=32.0.0,<35.0.0
    - kubernetes_asyncio >=32.0.0,<35.0.0

test:
  imports:
    - airflow.providers.cncf.kubernetes
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-cncf-kubernetes for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
