context:
  name: apache-airflow-providers-cncf-kubernetes
  version: "10.12.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_cncf_kubernetes-${{ version }}.tar.gz
  sha256: d7db527ccb2ceef560f0939a6c9f9eb40f7f60fd07ed26f4803fd9125c5f87b3

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core ==3.12.0
  run:
    - python >=${{ python_min }}
    - aiofiles >=23.2.0
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-compat >=1.10.1
    - asgiref >=3.5.2
    - cryptography >=41.0.0,<46.0.0
    - python-kubernetes >=32.0.0,<35.0.0
    - urllib3 >=2.1.0,!=2.6.0
    - kubernetes_asyncio >=32.0.0,<35.0.0

tests:
  - python:
      imports:
        - airflow.providers.cncf.kubernetes
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-cncf-kubernetes for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
